version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
    - 25565:25565
    - 25575:25575
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.12.2
#      JVM_XX_OPTS: "-XX:MaxRAMPercentage=75"
      MEMORY: ""
    tty: true
    deploy:
      resources:
        limits:
          memory: 6G
    stdin_open: true
    restart: unless-stopped
    volumes:
    # attach a directory relative to the directory containing this compose file
    - ./data/server:/data

#  creeper-farm-bot:
#    build: bot
#    #   container_name: 'MinecraftConsoleClient'
#    volumes:
#    - './data/bot:/opt/data'


  webmap:
    image: nginx
    ports:
     - 25566:80
    volumes:
    - './data/webmap:/usr/share/nginx/html'

